--- {board: eva_zm1, docs: 'https://docs.zerynth.com/latest/hardware/', name: ZM1
        Evaluation Board, phys_id: 20627b3c8179e8873a148468a012ebaaf5b2503c, pinmap: 'https://docs.zerynth.com/latest/hardware/',
    short_name: ZM1-EVA, specs: zf, uid: 20627b3c8179e8873a148468a012ebaaf5b2503c,
    version: v3.0.12}
...
